.PHONY: dev
dev:
	echo "TODO"

.PHONY: format
format:
	npx prettier --write "./src/**/*.{js,ts}"

.PHONY: serve
serve:
	npx ts-node ./src/index.ts

.PHONY: migrate
migrate:
	npx ts-node ./src/scripts/migrate.ts
